[package]
name = "sui_test_proj1"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
#Sui = { local = "../../../MystenLabs/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
sui_test_proj1 = "0x0"
#sui = "0000000000000000000000000000000000000000000000000000000000000002"
